version: "3"

services:
  linedesign:
    image:  linedesign:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: linedesign
    environment:
      TZ: Asia/Tokyo
      PIPENV_PIPFILE: /home/admin/linedesign/Pipfile
    ports:
      - 10090:10090
    user: root
    command: ['./wait-postgres.sh', 'postgresql', '/bin/bash -c "/home/admin/linedesign/scripts/start_web.sh"']
    # command: /sbin/init
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10.8
    container_name: postgresql_linedesign
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
